[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arfatnaik0", email = "arfatnaik05@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[all]>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
